### ISSUE TITLE
help

### ISSUE THREAD

**Issue by M0ck4ry** [mobaidoctor/polyp-ddpm#3]
Hello, I couldn't find the evaluation indicators in your paper. How can I evaluate its performance? If you could reply, I would greatly appreciate it

**Comment by mobaidoctor** [comment]
Hi, thank you for reaching out to us. We briefly described this in the "EXPERIMENTS AND RESULTS" section of our paper (https://arxiv.org/abs/2402.04031) on the second page. Regarding the segmentation model, we followed the approach for evaluation presented by Macháček R. et al., 2023 (https://arxiv.org/abs/2304.05233), in order to compare the efficacy of model performance in a fair manner. For quantitative evaluation, we utilized the torch-fidelity tool (https://github.com/toshas/torch-fidelity) to calculate the FID, IS, and KID. If you have any further questions or require clarification, please feel free to contact us.

**Comment by M0ck4ry** [comment]
wow Thank you for your reply. I am very happy and excited. As a learner, your reply greatly enhances my understanding of this field and gives me greater motivation to learn! Thank you again

**Comment by M0ck4ry** [comment]
wow Thank you for your reply. I am very happy and excited. As a learner, your reply greatly enhances my understanding of this field and gives me greater motivation to learn! Thank you again
