### ISSUE TITLE
Question about multi class training

### ISSUE THREAD

**Issue by wonkicho** [mobaidoctor/polyp-ddpm#5]
how can i train with multi class in this model?
i think that i should change input channel, but if revise default channel (6), it occurs error

can you help with this question?

**Comment by mobaidoctor** [comment]
Hi, thank you for your inquiry and for bringing a minor bug in our code to our attention. You can train our model using a multi-label segmentation mask in 2 ways. First, you can use our current code without any modifications, which would work as well, though the quality of synthetic images might not be similar to those produced by the model trained with one-hot encoded mask images. Secondly, you can increase the input channel. The reason you encountered an error when increasing the input channel was due to a hard-coded number in the return statement of the create_model function in diffusion_model/unet.py. We have already updated our code to: "return UNetModel(
    image_size=image_size,
    in_channels=in_channels,
    ...".  If you have any further questions, please feel free to contact us.
