### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Saint-lsy** [mobaidoctor/polyp-ddpm#6]
Could you please release pre-trained checkpoints of PolypDDPM? I hope to follow your excellent work. Thank you so much.

**Comment by mobaidoctor** [comment]
@Saint-lsy Hi, sorry for our late response. Thank you for your interest in our work and your inquiry regarding our pretrained model weights. As our Polyp-DDPM model can be quickly converged with any 2D image dataset, we initially did not release the weights, assuming it would be easy for users to train the model themselves. However, since you requested it, we have made the pretrained weights available. If you have any questions or need further clarification, please feel free to contact us. If you find our code and model weights helpful to your research, please consider citing our work. We would greatly appreciate it. Thank you.

**Comment by Saint-lsy** [comment]
Thanks so much！
